name: Run tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test:
    strategy:
      fail-fast: true
      matrix:
        os-version: [ 'ubuntu-latest', 'windows-latest' ]

    runs-on: ${{ matrix.os-version }}

    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
    - if: matrix.os-version == 'ubuntu-latest'
      name: Set TESTING environment variable (ubuntu)
      run: echo "TESTING=True" >> $GITHUB_ENV
    - if: matrix.os-version == 'windows-latest'
      name: Set TESTING environment variable (windows)
      run: echo "TESTING=True" >> $env:GITHUB_ENV

    - name: Set up Python
      uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
      with:
        cache: 'pip' # caching pip dependencies
        python-version-file: '.python-version'
    - name: Install uv
      uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39 # v8.2.0
      with:
        # Install a specific version of uv.
        version: "0.11.23"
        enable-cache: true
    - name: Install Python Dependencies
      run: uv sync --locked --all-extras
    - name: Run Django system check
      run: uv run --locked python manage.py check
    - name: Collect static files
      run: uv run --locked python manage.py collectstatic --noinput
    - name: Run KMUHelper Tests
      run: uv run --locked python manage.py test kmuhelper_tests
